import { Transaction } from '@/types/transaction';

export const transactionData: Transaction[] = [
  {
    id: '1',
    date: '2024-12-01',
    category: '売上',
    description: 'クライアントA案件',
    amount: 150000,
    type: 'income',
  },
  {
    id: '2',
    date: '2024-12-03',
    category: '経費',
    description: 'サーバー代',
    amount: 5000,
    type: 'expense',
  },
  {
    id: '3',
    date: '2024-12-05',
    category: '売上',
    description: 'クライアントB案件',
    amount: 200000,
    type: 'income',
  },
  {
    id: '4',
    date: '2024-12-07',
    category: '経費',
    description: '通信費',
    amount: 8000,
    type: 'expense',
  },
  {
    id: '5',
    date: '2024-12-10',
    category: '経費',
    description: '文房具',
    amount: 3000,
    type: 'expense',
  },
  {
    id: '6',
    date: '2024-12-15',
    category: '売上',
    description: 'クライアントC案件',
    amount: 180000,
    type: 'income',
  },
  {
    id: '7',
    date: '2024-12-18',
    category: '経費',
    description: 'ソフトウェアライセンス',
    amount: 12000,
    type: 'expense',
  },
  {
    id: '8',
    date: '2024-12-20',
    category: '売上',
    description: 'クライアントD案件',
    amount: 220000,
    type: 'income',
  },
  {
    id: '9',
    date: '2024-12-22',
    category: '経費',
    description: '交通費',
    amount: 4500,
    type: 'expense',
  },
  {
    id: '10',
    date: '2024-12-25',
    category: '経費',
    description: '書籍代',
    amount: 6000,
    type: 'expense',
  },
];
